== 관리자 인증 API

=== 관리자 로그인

SUPER_ADMIN 계정으로 로그인합니다.

로그인 성공 시 `adminAccessToken`, `adminRefreshToken` HttpOnly 쿠키가 발급됩니다.

operation::admin/login[snippets='http-request,request-fields,http-response,response-fields']

=== 관리자 토큰 갱신

`adminRefreshToken` 쿠키로 새로운 `adminAccessToken` 쿠키를 발급합니다.

operation::admin/refresh[snippets='http-request,http-response,response-fields']

=== 관리자 로그아웃

현재 로그인한 SUPER_ADMIN 계정의 refresh token을 삭제하고 관리자 인증 쿠키를 만료시킵니다.

operation::admin/logout[snippets='http-request,http-response']

=== 사용자 관리 - 조회

전체 누적 사용자 수와 선택한 가입 기간의 사용자 수 및 사용자 목록을 조회합니다.
가입 시작일과 종료일은 선택값이며, 한쪽 날짜만 입력한 조회도 가능합니다.

operation::admin/user/get-users[snippets='http-request,query-parameters,http-response,response-fields']

=== 게시글 관리 - 조회

게시글 목록을 조회합니다. 카테고리 및 키워드(제목 키워드, 유저명)를 통해 검색이 가능합니다.
카테고리와 키워드는 null값이 가능합니다.

operation::admin/post/get-posts[snippets='http-request,http-response,response-fields']


=== 게시글 관리 - 삭제

부적절한 게시글을 삭제합니다.

operation::admin/post/delete-post[snippets='http-request,http-response']

