== 유저 API
=== 프로필 조회

프로필 정보를 조회합니다.

operation::user/get-profile[snippets='http-request,http-response,response-fields']

=== 닉네임 수정

닉네임을 수정합니다. 응답으로 수정된 프로필 정보를 반환합니다.

operation::user/update-nickname[snippets='http-request,http-response,response-fields']

=== 내 모아방 게시글 조회

내가 작성한 모아방 게시글 목록을 조회합니다.

operation::user/get-my-moabang-posts[snippets='http-request,query-parameters,response-body,response-fields']

=== 내 자유게시판 게시글 조회

내가 작성한 자유게시판 게시글 목록을 조회합니다.

operation::user/get-my-free-posts[snippets='http-request,query-parameters,response-body,response-fields']

=== 내 댓글 조회

내가 작성한 댓글 목록을 조회합니다.

operation::user/get-my-comments[snippets='http-request,query-parameters,response-body,response-fields']

=== 내 관찰일지 조회

내가 작성한 관찰일지 목록을 조회합니다.

operation::user/get-my-observations[snippets='http-request,query-parameters,response-body,response-fields']

=== 북마크 한 게시글 조회

내가 북마크한 게시글 목록을 조회합니다.

operation::user/get-my-bookmarked-posts[snippets='http-request,query-parameters,response-body,response-fields']

=== 관찰일지 및 북마크 통계 조회

내가 생성한 관찰일지 총 갯수와 북마크한 게시글 총 갯수를 조회합니다.

operation::user/get-my-activity-counts[snippets='http-request,response-body,response-fields']